export const Config = {
  DEFAULT_RADIUS_METERS: 100,
  MIN_RADIUS_METERS: 25,
  MAX_RADIUS_METERS: 500,
  EMERGENCY_NUMBER: '911',
  GEOFENCE_TASK_NAME: 'SHUL_LOCK_GEOFENCE_TASK',
  NOTIFICATION_CHANNEL_ID: 'shul-lock-active',
};
